version: '3'
services:
  server_1:
    build: ./dockerfiles/server
    ports:
    - 5001:5000
  server_2:
    build: ./dockerfiles/server
    ports:
    - 5002:5000
  nginx:
    build: ./dockerfiles/loadbalancer
    ports:
    - 8080:80
    depends_on:
    - server_1
    - server_2
