name: Docker Compose Actions Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Install ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
      - name: Run ngrok
        run: ./ngrok http 8080
      - name: Run load generator
        run: python3 tools/load_generator/load_generator.py -a localhost:8080 -n 5
