name: Example usage of loadbalancer
on:
  workflow_dispatch:
    inputs:
      num_servers:
        description: Number of servers serving the requests
        required: True
      num_packets:
        description: Number of packets to send
        required: True
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare configs
        run: |
          pip3 install wheel
          pip3 install -r requirements.txt
          ./entrypoint.py ${{ github.event.inputs.num_servers }}
      - name: Build and run servers
        run: docker-compose up -d
      - name: Run load generator
        run: |
          python3 tools/load_generator/load_generator.py -a localhost -n ${{ github.event.inputs.num_packets }}
      - name: Print docker-compose logs
        run:
          docker-compose logs
      - name: Analyse docker-compose logs
        run: |
          echo -e "Requests sent: ${{ github.event.inputs.num_packets }}\n"

          for num in {1..${{ github.event.inputs.num_servers }}}
          do
            echo "Requests served by server $num:" $(docker-compose logs | grep "server_${num}_1.*GET.*" | wc -l)
          done
