name: Docker Compose Actions Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run entrypoint.py
        run: |
          sudo apt-get install gcc libpq-dev -y
          sudo apt-get install python-dev  python-pip -y
          sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
          pip3 install wheel
          pip3 install -r requirements.txt
          ./entrypoint.py 2
      - name: Build the stack
        run: docker-compose up -d
      - name: Install ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
      - name: Run ngrok
        run: ./ngrok http -log stdout 8080 > ngrok.log &
      - name: Get ngrok address
        run: cat ngrok.log | grep -o "url=http:.*" | cut -c 12-
      - name: Run load generator
        run: |
          ping $(cat ngrok.log | grep -o "url=http:.*" | cut -c 12-) -c 5
          # python3 tools/load_generator/load_generator.py -a $(cat ngrok.log | grep -o "url=http:.*" | cut -c 5-) -n 5
