name: Docker Compose Actions Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Install ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
      - name: Run ngrok
        run: ./ngrok http -log stdout 8080 > ngrok.log &
      - name: Get ngrok address
        run: cat ngrok.log | grep -o "url=http:.*" | cut -c 5-
      - name: Run load generator
        run: |
          cat $(cat ngrok.log) | grep -o "url=http:.*" | cut -c 5- > NGROK_ADDRESS
          python3 tools/load_generator/load_generator.py -a NGROK_ADDRESS -n 5
